### ISSUE TITLE
The link to Zettlr on the FAQ page is 404

### ISSUE THREAD

**Issue by weakish** [GitJournal/GitJournal.github.io#1]
The link to Zettlr on [the FAQ page](https://gitjournal.io/support/) is https://gitjournal.io/support/zettlr.com, which results in 404.

I guess you intended to link it to `https://zettlr.com` but accidentally forgetting to type the `https://` prefix.

**Comment by vHanda** [comment]
oh!! Thank you so much. I'd been wondering why my analytics showed people visiting ` https://gitjournal.io/support/zettlr.com`. I was wondering who linked to it.

Fixed :)
