### ISSUE TITLE
Pricing mailng list returns a 400

### ISSUE THREAD

**Issue by TomFaulkner** [GitJournal/GitJournal.github.io#2]
When attempting to sign up for the mailing list, entering a first name and a email address a 400 is returned and the form is changed to display "Failed".

**Comment by vHanda** [comment]
This explains why I haven't had a single signups since end Nov! Thanks for reporting.

**Comment by vHanda** [comment]
Fixed

**Comment by TomFaulkner** [comment]
I don't know if you pushed the changes, but I am still getting a 400 with "name missing" when I use this form. The display is still "Failed."
